In [2]:
import numpy as np

## Numpy DataTypes and Attributes 🤯


In [9]:
# NumPy's main datatype is ndarray (n-dimenstion-array)
a1 = np.array([1,2,3])
a1


array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18] ] ])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [17]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.randint(0 , 10)
random_array
if random_array == 7:
    print("It's 7 Thala for reason 😂")
else:
    print(random_array)
    

It's 7 Thala for reason 😂
